// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQbLO5LHY2HQjnFcFt2WJnWP2br3gmtQ8',
    appId: '1:861316096193:web:14992dd9635f238cbe3440',
    messagingSenderId: '861316096193',
    projectId: 'chat-app-95f3c',
    authDomain: 'chat-app-95f3c.firebaseapp.com',
    storageBucket: 'chat-app-95f3c.appspot.com',
    measurementId: 'G-XYB6E70P1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAolVg3qQjKVvvuWPx1uAu9V-TsG5rQ8x8',
    appId: '1:861316096193:android:ea564451da4c418abe3440',
    messagingSenderId: '861316096193',
    projectId: 'chat-app-95f3c',
    storageBucket: 'chat-app-95f3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmtBve2Nn2arGGCvFGKWV43UfUN2yIZs',
    appId: '1:861316096193:ios:0430a2593cdc2320be3440',
    messagingSenderId: '861316096193',
    projectId: 'chat-app-95f3c',
    storageBucket: 'chat-app-95f3c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxmtBve2Nn2arGGCvFGKWV43UfUN2yIZs',
    appId: '1:861316096193:ios:f67fdff6bc934d78be3440',
    messagingSenderId: '861316096193',
    projectId: 'chat-app-95f3c',
    storageBucket: 'chat-app-95f3c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
